### ISSUE TITLE
How to scroll a scrollable element?

### ISSUE THREAD

**Issue by zerg000000** [clj-commons/etaoin#351]
I find that the `scroll*` functions only work for scrolling the browser, however, I don't find a way to scroll some scrollable element ( e.g. overflow: scrollX, scrollY ). Currently, I try to use js to emulate this behaviour. May I doing it right?

**Comment by igrishaev** [comment]
Hi @zerg000000 , thank you for your question. By default, we don't provide such a function to scroll an element. I think you may click on the element and then press DOWN several times. This combo might be composed with actions (please see the readme file). Also, please check the SO link below:

https://stackoverflow.com/questions/3401343/scroll-element-into-view-with-selenium

**Comment by lread** [comment]
I'm going to assume this one was answered.
If the question comes up again we might consider updating the user guide with a concrete example.
