### ISSUE TITLE
Implement print to PDF now that chrome and firefox now implement this part of WebDriver spec?

### ISSUE THREAD

**Issue by imbilltucker** [clj-commons/etaoin#355]
In the [Webdriver spec](https://www.w3.org/TR/webdriver/#print), there is a print function to generate a PDF of the current webpage.   Both chrome and firefox now support this print-to-pdf command.

I don't see this implemented in etaion.   Did I miss it?   Can it be added?

Here's the corresponding issue in Selenium:  https://github.com/SeleniumHQ/selenium/issues/8802

**Comment by jakemcc** [comment]
In case anyone else sees this issue and wants to do this, it was pretty easy to implement on top of `etaoin.api/execute`. This hasn't been battle tested but it something I'm using in a personal project.

```clojure
(let [pdf-data (etaoin.api/execute {:driver driver
                                    :method :post
                                    :path [:session (:session driver) :print]})]
  (if (zero? (:status pdf-data))
    {:data (:value pdf-data)}
    {:error (:value pdf-data)}))
```

**Comment by lread** [comment]
Thanks @imbilltucker (and @jakemcc) I'll follow up with a PR with print support.
