### ISSUE TITLE
Disabling javascript with a profile doesn't work in chrome headless mode

### ISSUE THREAD

**Issue by RickMoynihan** [clj-commons/etaoin#363]
The [README](https://github.com/igrishaev/etaoin#setting-browser-profile) states:

> Imagine you'd like to run your integration tests against a user that turned off Javascript execution or image rendering. To prepare a special profile for that task would be a good choice.

I followed the steps outlined to create a chrome profile which disables javascript, then I started chrome in headed mode like this:

```clojure
(def default-params {:args ["--no-sandbox" "--disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies"], :size [1280 960], :download-dir "/Users/rick/repos/muttnik/tmp/webdriver-downloads", :profile ".chrome-config/config/NoJavascriptProfile"})
  
  (def nojsdriver (et/chrome (assoc default-params
                              :headless false)))

  (et/go nojsdriver "http://localhost:3000/data")

  (map (partial et/get-element-text-el nojsdriver) (et/query-all nojsdriver {:css "noscript"}))
  ;; => ("JavaScript is not enabled in your browser so you're missing out on some features.")

  (et/quit nojsdriver)
```

The above works as expected; the noscript tag is rendered and visible in screenshots and via the selector above.

However setting `:headless true` and rerunning the same code does not appear to work:

```clojure
(def nojsdriver (et/chrome (assoc nojs-driver-config
                                    :headless true)))

  (et/go nojsdriver "http://localhost:3000/data")

  (map (partial et/get-element-text-el nojsdriver) (et/query-all nojsdriver {:css "noscript"})) ;; => ("")

  (et/quit nojsdriver)
```

Note the `<noscript>` selector returns `("")`.

I appreciate this appears to be an issue with chromes webdriver.  [Various stackoverflow](https://stackoverflow.com/questions/47066614/how-to-disable-javascript-in-chrome-headless-using-php-webdriver) posts etc seem to indicate similar issues in the past; though no issues I've seen appeared to go via the profile route suggested in your README.

I do not know for sure if this is possible or not; but it might be worth at least weakening the statement in the README to clarify that the integration tests for chrome must run with `:headless false` otherwise it will not work, and is unsuited to many CI environments.

**Comment by lread** [comment]
@RickMoynihan thanks for raising this issue.

I'm learning that there are many nuances and variations for the various WebDriver implementations. I could add a general statement on this to the troubleshooting section with this specific example.
