### ISSUE TITLE
Chrome driver did not work with the Default profile

### ISSUE THREAD

**Issue by amivanoff** [clj-commons/etaoin#374]
It looks like type coersion from String to File with type hint did not work on Java 16-17, clojure 1.10.3 and etaoin 0.4.6.

`(def ^File profile123 "C:/Users/user/AppData/Local/Google/Chrome/User Data 4/Default")`

It returns String and all ends up with an exception like this:

`Execution error (ClassCastException) at etaoin.driver/eval14433$fn (driver.clj:164).
class java.lang.String cannot be cast to class java.io.File (java.lang.String and java.io.File are in module java.base of loader 'bootstrap')`

**Comment by amivanoff** [comment]
As a workaround, do not use Default profile, create another one, like "Profile 1" and then config with
`:user-data-dir "c:/user/amiva/AppData/Local/Google/Chrome/User Data 4"
:profile "C:/Users/user/AppData/Local/Google/Chrome/User Data 4/Profile 1"`
works well.

**Comment by lread** [comment]
Hi @amivanoff thanks for raising this issue.

Putting that `^File` on that var won't coerce it from a string to a `File`.

```Clojure
(import 'java.io.File)

(def ^File foo "123")
(type foo)
;; => java.lang.String

;; but it still might confuse things
(meta #'foo)
;; => {:tag java.io.File,
;;     :line 39,
;;     :column 1,
;;     :file "/Users/lee/proj/oss/clj-commons/etaoin/fiddle/issue378.clj",
;;     :name foo,
;;     :ns #namespace[user]}

;; if you want to convert a string path to a file you can do this
(require '[clojure.java.io :as io])

(def foo2 (io/file "123"))
(type foo2)
;; => java.io.File
```

All that said, as I understand it, `:profile` expects a string value.
If you omit `^File` I expect all would work.

I'm going to go ahead and close this one, but please do respond and/or re-open if you feel I've not addressed the issue you raised.
