### ISSUE TITLE
Race condition when binding to a free socket

### ISSUE THREAD

**Issue by john-shaffer** [clj-commons/etaoin#379]
[get-free-port](https://github.com/igrishaev/etaoin/blob/9f07e3098a8e152a7998438718c631e85fe0ba05/src/etaoin/util.clj#L43-L46) finds a free port, but does not hold on to it. etaoin later uses this port, but sometimes the port is no longer available and at that point etaoin throws.

**Comment by lread** [comment]
Thanks for raising the issue @john-shaffer, are you proposing that we should check and select a free port closer to the time it will be used?

Ideally, we'd just launch a WebDriver process, ask it to choose a free port, and then use that.

But, I had a little peek at chromedriver, geckodriver, safaridriver, and msedgedriver.
Looks to me like only geckodriver supports asking the WebDriver to select port.

**Comment by lread** [comment]
@john-shaffer I'm going to go ahead and close this one.

The only thing I can think of to avoid concurrency issues is to take the assignments of ports more into your hands than Etaoin's.

If you can think of other ideas, or I've missed the mark here, please do feel free to reply/re-open this issue.
