### ISSUE TITLE
An etaoin logo might be nice

### ISSUE THREAD

**Issue by lread** [clj-commons/etaoin#399]
## Etaoin Deserves a Logo

But what would it look like?

Etaoin is like qwerty but for linotype machines and laid out vertically instead of horizontally.

If I've understood, the idea behind the name is that you press keys, and some magical and perhaps complex machinery activates.

## Linotype Machines
Maybe these images will spark some ideas.

Here's one of these old linotype beauties:
![image](https://user-images.githubusercontent.com/967328/168301063-a3fe90c1-29a5-48d7-bbd4-a7236ce7b635.png)
([source](https://www.gutenberg.org/files/41160/41160-h/images/i358.jpg))

The keyboard looks like:
![image](https://user-images.githubusercontent.com/967328/168302169-128131ea-dba6-435b-ae22-403f3bf56397.png)
([source](https://commons.wikimedia.org/wiki/File:Linotype_keyboard_with_Star_Quadder_attachment.jpg))

## Logo Goals
Something that renders to a small icon is nice and reusable in many places.
(or that also has a recognizable square version)

## Initial Brain Ramblings

- etaoin as rendered as linotype keys horizontally
- etaoin rendered vertically (as in a real linotype keyboard) with a finger about to press one of the keys
- steampunk
- Rube Goldberg
- gears, pulleys, etc
- old-timey linotype operator person
- more ideas are most welcome!

**Comment by igrishaev** [comment]
My five cents: I was thinking about a metal fort which was used for those machines. Say, the word "ETAOIN" composed from such things:

![depositphotos_42227421-stock-photo-metal-type-printing-press-typeset](https://user-images.githubusercontent.com/1059232/168415714-ff46b003-154b-450e-b3f6-8114def9ff4f.jpg)
![images](https://user-images.githubusercontent.com/1059232/168415716-f8aa873b-e42e-46b4-ad0f-4b7bd736d707.jpeg)
![download](https://user-images.githubusercontent.com/1059232/168415719-f6129168-1762-460a-8772-cd0ec5dda707.jpeg)

**Comment by igrishaev** [comment]
I even though on buying such a collection of characters on Ebay, compose the title and make a photo.

**Comment by lread** [comment]
Cool! I'm just learning about linotype machines.

I was thinking of the slugs which would have the letters mirrored so that they print correctly:
![image](https://user-images.githubusercontent.com/967328/168436120-14949114-61ad-41b6-8f3b-3ffd686d3961.png)
([source](https://commons.wikimedia.org/wiki/File:Linotype_Matrix_Transposition_Error_(crop).JPG))

But the thing that produces the slugs (the matrix?) would not be mirrored:
![image](https://user-images.githubusercontent.com/967328/168435440-46b08200-4bc0-47a4-a79c-ddb7f48a74dc.png)
([source](https://commons.wikimedia.org/wiki/File:Duplexed_Linotype_matrices_regular_and_bold.jpg))

But of course, we have complete artistic license and don't need to pedantically adhere to any reality for a logo.

**Comment by lread** [comment]
A simple idea is to base the logo on the print etaoin would produce from a linotype machine:
![image](https://user-images.githubusercontent.com/967328/168442421-5405269b-26a1-4d32-87b2-4ea42c13f5f3.png)
([source](https://en.wikipedia.org/wiki/Etaoin_shrdlu))

**Comment by igrishaev** [comment]
A very draft preview:
![Frame 1](https://user-images.githubusercontent.com/1059232/168491574-cb07da59-aa9d-4620-ae26-8e944ebb60bd.jpg)

That's not a logo though but rather a banner picture. For the logo, I have one idea that I'll publich here a bit later.

**Comment by lread** [comment]
Nice! Very creative!

Can we find open-source imagery or will we need to draw/generate our own?

**Comment by igrishaev** [comment]
Well, I'm going to buy that image and make a clear version of it without artefacts and watermark.

**Comment by lread** [comment]
Ah! I see now. Looking forward to your creations!

**Comment by lread** [comment]
Thanks to @igrishaev, closed by 9a5661952b49ae3e1813fbeee16cc82bdd5f5a2a
