### ISSUE TITLE
Create a clj-kondo export config

### ISSUE THREAD

**Issue by lread** [clj-commons/etaoin#413]
## Opportunity
A clj-kondo export config will help users of Etaoin who also use clj-kondo find mistakes more readily in their source code.

## Macros
Etaoin exposes a number of macros in its public API.
Clj-kondo needs a little help to lint macros it is unaware of.

Sometimes when a library's macro signature and its bindings are similar to existing clj-kondo lint rules, one can get away with doing a `:lint-as` existing lint rule.

Other times you need to write clj-kondo hooks to teach clj-kondo about the effect of your macros.
This seems to be the case for Etaoin.

As part of #411, I added clj-kondo `:macroexpand` hooks.
I feel these are fine for internal use, but their reporting is much coarser grained than it could be if the hooks were implemented as `:analyze-call` hooks.

**Comment by lread** [comment]
Etaoin exposes all publics in its documented public API (as far as I can tell no public API or namespace is considered internal and unsupported).

Here's our current list of macros. 
I've marked the ones that have binding side effects (or similar) with :b:. 
We'll likely want to deal with those via `:analyze-call` hooks.

For the rest maybe we can get away with using `:macroexpand` hooks?
For example `with-pointer-left-btn-down` has no binding side effect, but telling clj-kondo about it allowed clj-kondo to make sense of it when used in a threading macro https://github.com/clj-commons/etaoin/blob/f3f5248f9d3809e6a9013f1a2a7f7ff0e786058c/test/etaoin/unit_test.clj#L59-L64

Anyway, there are clear fn signature patterns that could be reused.

- eatoin.api
  - (doto-wait n obj & body)
  - (when-chrome driver & body)
  - (when-edge driver & body)
  - (when-firefox driver & body)
  - (when-headless driver & body)
  - (when-not-chrome driver & body)
  - (when-not-driver browsers driver & body)
  - (when-not-edge driver & body)
  - (when-not-firefox driver & body)
  - (when-not-headless driver & body)
  - (when-not-phantom driver & body)
  - (when-not-safari driver & body)
  - (when-phantom driver & body)
  - (when-predicate predicate & body)
  - (when-safari driver & body)
  - :b: (with-chrome opt bind & body) 
  - :b: (with-chrome-headless opt bind & body)
  - (with-css driver & body)
  - :b: (with-driver tyhpe opt bind & body)
  - :b: (with-edge opt bind & body)
  - :b: (with-edge-headless opt bind & body)
  - (with-exception catch fallback & body)
  - :b: (with-firefox opt bind & body)
  - (with-frame driver q & body)
  - (with-key-down input key & body)
  - (with-locator driver location & body)
  - (with-mouse-btn driver & body)
  - :b: (with-phantom opt bind & body)
  - (with-pointer-btn-down input button & body)
  - (with-pointerleft-btn-down input & body)
  - (with-postmortem driver opt & body)
  - :b: (with-safari opt bind & body)
  - (with-screenshots driver dir & body)
  - (with-script-timeout driver sec & body)
  - (with-wait n & body)
- etaoin.api2
  - :b: (with-chrome [bind & [options]] & body) 
  - :b: (with-chrome-headless [bind & [options]] & body)
  - :b: (with-edge [bind & [options]] & body)
  - :b: (with-edge-headless [bind & [options]] & body)
  - :b: (with-firefox [bind & [options]] & body)
  - :b: (with-firefox-headless [bind & [options]] & body)
  - :b: (with-phantom [bind & [options]] & body)
  - :b: (with-safari [bind & [options]] & body)
- etaoin.client
  - (with-pool opt & body)
- etaoin.util
  - :b: (defmethods multifn dispatch-vals & fn-tail)
  - :b: (with-tmp-dir prefix bind & body)
  - :b: (with-tmp-file prefix suffix bind & body)

**Comment by borkdude** [comment]
I'm trying to improve the macroexpand hook, see:
https://github.com/clj-kondo/clj-kondo/issues/1701#issuecomment-1133222340

It's not clear to me which macros beyond those with B need extra help from hooks?
e.g. `(with-pool ... ...)` should not give any problems, or does it?

**Comment by lread** [comment]
Thanks for the reply @borkdude, I originally thought I'd only have to deal with the macros that did the bindings, but added, for example `with-pointer-left-btn-down`: https://github.com/clj-commons/etaoin/blob/1e0c80fc55abc3a357651a89791958a88237e6ac/.clj-kondo/etaoin/api.clj#L17-L22

to clj-kondo's brains via `:macro-expand`: https://github.com/clj-commons/etaoin/blob/1e0c80fc55abc3a357651a89791958a88237e6ac/.clj-kondo/config.edn#L12

Without this clj-kondo config, the following code: https://github.com/clj-commons/etaoin/blob/1e0c80fc55abc3a357651a89791958a88237e6ac/test/etaoin/unit_test.clj#L60-L65

Returns the following findings:
```shell
$ clj-kondo --lint test
test/etaoin/unit_test.clj:64:31: error: etaoin.api/add-pointer-move-to-el is called with 1 arg but expects 2 or more
linting took 146ms, errors: 1, warnings: 0
```

**Comment by borkdude** [comment]
But why do you have to add a custom hook for `with-pointer-left-btn-down ` at all? If you leave that out, what do you get? I don't see a syntactical problem there yet.

**Comment by lread** [comment]
I didn't understand it, but without it, I get the finding from clj-kondo that I showed in the comment above.
My thinking was, oh a macro, I guess clj-kondo needs a hook.
But maybe clj-kondo should not need the hook here?

**Comment by borkdude** [comment]
@lread Can you give a standalone snippet here including the ns form, which I can lint with `clj-kondo --lint example.cljs`?

**Comment by lread** [comment]
Ok, I've taken a stab at distilling.

In a new empty directory, given file `example.clj`:
```Clojure
(ns example)

;;
;; original code for reference
;;
#_
(-> (make-mouse-input)
    add-pointer-click
    add-pause
    (with-pointer-left-btn-down
      (add-pointer-move-to-el "123"))
    (dissoc :id))

#_
(defmacro with-pointer-left-btn-down
  [input & body]
  `(-> ~input
       add-pointer-down
       ~@body
       add-pointer-up))

#_
(defn add-pointer-move-to-el
  [input el & [{:keys [duration]}]]
  (add-pointer-move input {:duration duration
                           :origin   (el->ref el)}))


;;
;; An attempt at distilling
;;
(defmacro my-macro [input & body]
  `(-> ~input ~@body))

(defn my-fn [_input _el]
  'whatever)

(-> 'something
    (my-macro
      ;; clj-kondo finds a problem here on line 41:
      (my-fn "123")))
;; => whatever

;;
;; Macro expanded, the code looks fine
;;
(macroexpand
  '(-> 'something
       (my-macro
         (my-fn "123"))))
;; => (my-fn 'something "123")
```
Run:
```Shell
$ clj-kondo --lint example.clj
example.clj:41:7: error: example/my-fn is called with 1 arg but expects 2
linting took 10ms, errors: 1, warnings: 0
```

Watcha think?

**Comment by borkdude** [comment]
It seems `my-macro` can be linted as `clojure.core/->`

Adding this `{:clj-kondo/config '{:lint-as {etaoin/my-macro clojure.core/->}}}` seemed to solve the problem.

**Comment by lread** [comment]
Ah! Thanks!
