### ISSUE TITLE
Automate release workflow

### ISSUE THREAD

**Issue by lread** [clj-commons/etaoin#422]
## Currently
As far as I can tell, the Etaoin release workflow is executed manually.

## But...
For me, this is too error-prone.

## So..
I'd like to entirely automate this and release from CI.

Two options I've used in the past:
1. A GitHub Actions release workflow that is initiated by pressing a button in the GitHub Actions UI. [Example on for rewrite-clj](https://cljdoc.org/d/rewrite-clj/rewrite-clj/1.0.767-alpha/doc/maintainer-guide#_releasing).
2. A release triggered by tag push (triggered by some "deploy" or "publish" command on the command line).

## Scope
- Maintainers guide documentation that describes the workflow and how to release
- Versioning scheme. Might be nice to continue with the current scheme, but we'll go with the recent flow and bump the `major` version from `0` to `1`. Not sure what the current strategy is for `minor` and `patch`. I think maybe `minor` is currently maybe breaking and `patch` is simple incrementing non-breaking.

**Comment by lread** [comment]
https://github.com/liquidz/build.edn looks very interesting. 
Will take a peek at it for this work.

**Comment by lread** [comment]
From chat with @borkdude: He proposes patch simply be the release count. 
I like this more this commit count which can:
- require fiddling to compensate for doc updates
- can get large and therefore harder to hold in the brain for users.

**Comment by lread** [comment]
More helpful notes from @borkdude: https://gist.github.com/borkdude/c803b5b59979429a6e92cd4b8956c2c8

**Comment by lread** [comment]
Given there's a chance we might have gotten the public API wrong #441, I think our first v1 release should be marked `alpha`.

**Comment by borkdude** [comment]
Meh, I'd say we just release 0.4.1 (or 0.4.release-count) and get it over with. There will be bugs and they will get fixed in a next release. With rewrite-clj we're still on alpha. The newest clojure.data.xml has been alpha for years. But given that everybody is using this, alpha doesn't really say anything.

**Comment by lread** [comment]
Ya, I like the `release-count` idea and am happy to go with that.

I guess `alpha` might stop some folks from even trying the release, so that's a good argument against it. I was ultra careful with rewrite-clj because it is such a foundational lib. Maybe that does not apply so much here.

I like the idea of moving to v1.

Have got my head still deep in the user guide, so it might be a bit before I actually cut the next release.
