### ISSUE TITLE
Broken link in the README

### ISSUE THREAD

**Issue by viebel** [clj-commons/etaoin#479]
The link to the Wikipedia page that gives its name to this library is https://en.wikipedia.org/wiki/Etaoin_shrdlu#Literature. But there is no `#Literature` hash tag in this Wikipedia page.

What's the origin of the library name then?

**Comment by lread** [comment]
Huh! Interesting, thanks for noticing @viebel!

If I look at [the history of that wikipedia page](https://en.wikipedia.org/w/index.php?title=Etaoin_shrdlu&action=history), there used to be a literature section.

There's an [older version of the page](https://en.wikipedia.org/w/index.php?title=Etaoin_shrdlu&oldid=1028346468) that does include a literature heading.

From an old chat with Ivan (the founder of of Etaoin), he did recommend I read "Etaoin Shrdlu" so I'm gonna guess it might be the short story by Fredric Brown.  

Hey, I might have actually found a [readable copy here](https://archive.org/details/Unknown_v05n05_1942-02_slpn/page/n65/mode/1up).

**Comment by viebel** [comment]
Would you like to update the README accordingly?

**Comment by lread** [comment]
Yup, will do.
