### ISSUE TITLE
Execution error (IllegalArgumentException)

### ISSUE THREAD

**Issue by mikeananev** [clj-commons/etaoin#503]
**Version**
1.0.38

**Platform**
Operating System: macOS m1 12.2.1
Clojure version: 1.11.1
JDK vendor and version:19.0.1

Browser vendor: [Chrome, Firefox]
WebDriver version: [ChromeDriver 107.0.5304.62, geckodriver 0.32.0]

**Symptom**
Can't load any driver because of bug in code.

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/45389186/203795707-26bfc184-f1fb-43a9-b091-608a818ad883.png">

**Reproduction**
```clojure
(ns com.example.ui
  (:require [etaoin.api :as e]
            [etaoin.keys :as k]))

;; Start WebDriver for Chrome
(def driver (e/chrome))
```

**Actual behavior**
Got Exception

**Expected behavior**
Should load driver.

**Diagnosis**

The function etaoin.api/wait has a bug in  code. Linter says "Cannot disambiguate overloads Thread/sleep.."

<img width="592" alt="image" src="https://user-images.githubusercontent.com/45389186/203796983-46d19973-51b2-4cd0-a38c-610fc8ac884f.png">

**Action**

To fix the bug we need to put metadata ^long.
Code should be like this. 

```clojure
(defn wait
  "Sleep for `seconds`."
  (#_{:clj-kondo/ignore [:unused-binding]} [driver seconds]
   (wait seconds))
  ([seconds]
   (Thread/sleep ^long (* seconds 1000))))
```

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/45389186/203797928-dbd97c59-bae7-4283-9926-4a0e3e45adad.png">

**Comment by lread** [comment]
Thanks @mikeananev for a great bug report! Will fix soon.

Note for the curious: This is a JDK19+ only interop issue.

**Comment by lotuc** [comment]
```Clojure
wsat.tasks.webdriver> (class etaoin.api/*wait-interval*)
java.lang.Double

wsat.tasks.webdriver> (etaoin.api/wait etaoin.api/*wait-interval*)
Execution error (IllegalArgumentException) at etaoin.api/wait (api.clj:2456).
No matching method sleep found taking 1 args
```

I encountered the same problem and just found that the default interval is Double (which is set to be `0.33`), it's used somewhere as default `wait` interval, and Java's `Thread/sleep` expected a long argument.
