### ISSUE TITLE
Process cleanup while starting webdriver process

### ISSUE THREAD

**Issue by lotuc** [clj-commons/etaoin#517]
I notice tons of zombie process (chromedriver) at my long running container with repeated task using etaoin.

After checking the source code, I think there might be a logic leak for recycling process here at:

https://github.com/clj-commons/etaoin/blob/9dd32cf3740ec7449f0d74d6ad475f9a2d6124b9/src/etaoin/api.clj#L3510-L3514

`run-driver` calls `-run-driver*` to start the webdriver process and do some retry logic. When `run-driver` returns, the caller (and the only caller) `boot-driver` do the process cleanup. But there **should be** some process cleanup logic here at Line `3514` to do cleanup also.

**Comment by lread** [comment]
Hmmm... Thanks for reporting @lotuc.

I think you are right... if the process unexpectedly dies we are fine, but if we timeout waiting for the process to be ready, then we make no attempt to kill the process.

The retry logic is only active by default for safari, (which can tend to error out on launch), but the flaw is still present when there is only a single attempt.

**Comment by lotuc** [comment]
Thanks for the quick response :).

Though this little logic flaw exists, but I guess that not the cause of my zombie process issue. Maybe there is some misuse in my application code.

**Comment by lread** [comment]
Still a good find @lotuc, thanks for that.

Perhaps useful to you, perhaps not: While developing on Etaoin I was often curious about zombie WebDriver processes and [wrote a bb task to list them and kill them](https://github.com/clj-commons/etaoin/blob/master/doc/02-developer-guide.adoc#webdriver-processes).

**Comment by lotuc** [comment]
Thanks for the tip!

After searching around, I found that the chromedriver seems have the problem for cleanly cleanup its related processes (google for keyword `chromedriver zombie process`).

And because I'm using it at docker container. I can just make [tini](https://github.com/krallin/tini) the init process and collects all the shutdown process (but not properly handled subprocesses - which becomes zombies) and handles the subprocess reaping job. As `tini` document says, for recent docker versions, It's default included, so I just need pass `--init` flag, and zombies gone.

**Comment by lread** [comment]
Good to know, thanks!

Perhaps when destroying a WebDriver process, we should make some effort to destroy child processes. [Babashka process does offer us destroy-tree](https://github.com/babashka/process/blob/master/API.md#destroy-tree-) which is JDK9+ only, but does cleanly fall back to our current behaviour.

**Comment by lread** [comment]
I think I'm seeing some good evidence of this failure to cleanup in failed CI tests.

Under "Complete Job" GitHub Actions is reporting:

```
Cleaning up orphan processes
Terminate orphan process: pid (4940) (conhost)
Terminate orphan process: pid (5468) (firefox)
Terminate orphan process: pid (992) (firefox)
Terminate orphan process: pid (1152) (firefox)
```
Not sure what `conhost` is a result of, but those `firefox` orphans are, I'm pretty sure, due to this issue.
