### ISSUE TITLE
Add get-element-outer-html[-el]

### ISSUE THREAD

**Issue by hendursaga** [clj-commons/etaoin#522]
It took me too long to realize that an issue I was stuck on was because I didn't realize there wasn't a way to grab the outer HTML instead of just the inner HTML.

It would seem to be a relatively straightforward copy-and-paste job, but I figured we'd discuss this before I try and code up a PR.

**Comment by lread** [comment]
Hi @hendursaga [raising an issue first is appreciated](https://github.com/clj-commons/etaoin/blob/master/doc/02-developer-guide.adoc#issue-first-please), thanks!

So `etaoin.api` currently exposes `get-element-inner-html` and `get-element-inner-html-el`, and you are proposing that to add `get-element-outer-html` and `get-element-outer-html-el`.

If that works across all of our supported webdriver implementations, coolio, PR welcome!

**Comment by hendursaga** [comment]
It appears it's [part of the official spec](https://w3c.github.io/webdriver/#dfn-outerhtml-idl-attribute), or at least, [a referenced spec](https://w3c.github.io/DOM-Parsing/#dom-element-outerhtml). I've never known an implementation to not allow grabbing the outer HTML.

In the meantime, my workaround is simply `e/get-element-property driver query :outerHTML)`

Is there a way for me to easily test out all these implementations?

**Comment by lread** [comment]
> Is there a way for me to easily test out all these implementations?

Feel free to submit a PR if you like. 
We have GitHub Actions test across all supported WebDrivers and OSes.

**Comment by lread** [comment]
I am reviewing the API for other reasons... and if I'm expecting that `get-element-inner-html-*` were added maybe by someone who was not aware/remembering that `get-element-property-*` exist.

If `get-element-inner-html-*` did not already exist, I would just beef up the docstrings for `get-element-property-*` to include common properties like `:innerHTML` and `:outerHTML`.

I think I might do that instead. I won't deprecate `get-element-inner-html-*` but their docstrings will be updated to point to `get-element-property-*`.
