### ISSUE TITLE
docs: better describe `etaoin.api/select` and its alternatives

### ISSUE THREAD

**Issue by boxxxie** [clj-commons/etaoin#534]
**Problem/Opportunity**

I couldn't use the select API to target the options that i wanted because my options shared copy/text and were differentiated by their value attribute. 

**Proposed Solution**
make select a bit smarter about matching by searching for more parts of the option tags like id, value, class, etc...
example of code that does a search for values and text and then falls back to previous select code.
```clojure
(defn select
  "Have `driver` select option with matching `text` for select element found by query `q`.
  The select element is clicked, then the option.
  See [[query]] for details on `q`."
  [driver q text]
  (let [select-el (e/query driver q)]
    (e/click-el driver select-el)
    (let [options (e/children driver select-el {:tag :option})]
      (if-let [selection (->> (concat
                               ;; this is a way of ranking node :value higher than node text
                               []
                               (->> options
                                    (filter (fn [el]
                                              (= text (e/get-element-attr-el driver el :value)))))
                               (->> options
                                    (filter (fn [el]
                                              (= text (e/get-element-text-el driver el))))))
                              first)
               ]
        (e/click-el driver selection)
        (e/select driver q text)))))
```

**Alternative Solutions**
let the user tell select how to search

**Action**
i think the code i proposed is a breaking change, so maybe there is a better way to write it up that isn't breaking, like maybe `text` could be a string or object, and if object then it's merged into a query options param.

**Comment by lread** [comment]
Hi @boxxxie, thanks for raising an issue.

`etaoin.api/select` is a convenience function that helps to select an `option` based on text. This is a common use case. I'll show you other ways to select options.

## Sample HTML
To demonstrate, I created some HTML to mimic your scenario in a`fiddle/slack20230404.html` file:

```html
<html>
<body>

<select id="myselect">
  <option value="bar">bar<option>
  <option value="foo1">foo</option>
  <option value="foo2">foo</option>
  <option value="foo3">foo</option>
</select>

</body>
</html>
```

## Playing in the REPL
Now to the REPL:

### Setup
```Clojure
;; setup
(require '[etaoin.api :as e] '[babashka.fs :as fs])

;; open a firefox browser
(def driver (e/firefox))

;; navigate to our sample HTML
(e/go driver (->> "fiddle/slack20230404.html" fs/absolutize (str "file://")))

;; check on the current value of myselect
(e/get-element-value driver :myselect)
;; => "bar"
```

### Using `select`
First, I want to reproduce your experience:
```Clojure
(e/select driver :myselect "foo")

;; it seems to select the first foo
(e/get-element-value driver :myselect)
;; => "foo1"
```

### Select an option by text without using `select`
And now I'll show you the equivalent without using `select`:
```Clojure
;; let's start afresh by refreshing the page
(e/refresh driver)
(e/get-element-value driver :myselect)
;; => "bar"

;; Now let's repeat what select is doing
(e/click driver :myselect) ;; only for safari compatibility
;; ...but this time use XPath syntax
(e/click driver ".//select[@id='myselect']/option[contains(text(),'foo')]")
(e/get-element-value driver :myselect)
;; => "foo1"
```

Let's do that again but use vector syntax:
```Clojure
(e/refresh driver)
(e/get-element-value driver :myselect)
;; => "bar"

(e/click driver :myselect) 
;; ...but this time use vector syntax
(e/click driver [{:tag :select :id :myselect} {:tag :option :fn/text "foo"}])
(e/get-element-value driver :myselect)
;; => "foo1"
```
So, the `select` function is a shorthand for a common use case.

### Select an option by attribute

Selecting option with value `foo2` via XPath:
```Clojure 
(e/click driver :myselect) ;; for safari compatibility, otherwise not required
(e/click driver ".//select[@id='myselect']/option[@value='foo2']")
(e/get-element-value driver :myselect)
;; => "foo2"
```
Selecting option with value `foo3` via vector syntax
```Clojure
(e/click driver [{:tag :select :id :myselect} {:tag :option :value "foo3"}])
(e/get-element-value driver :myselect)
;; => "foo3"
```

## Cleanup
```Clojure
;; we are done, so we close our session
(e/quit driver)
```

Does that make sense to you? 

Let me know. If this above works for you, I'll add a note to the docstring of the `etaoin.api/select` function to explain that it is a convenience function that is a shorthand.

**Comment by boxxxie** [comment]
thanks for the reply, but there are a few issues.

- if select worked the way you describe, i wouldn't have had a bad experience with it, but i still would have preferred value based selection.
- the way it currently works, and the way you think it should work, are both buggy. 
- the way you describe how to do things normally, without select, seem a bit overwhelming and verbose. seeing xpath in my debug output is ok, being forced to write xpath to use this type of API is too much, i think my example workaround shows that it's very easy to avoid doing something like that.
- if you are in control of the html, which i assume most people using this lib are, select by value is the only sane thing to do. text/copy changes based on business, or language settings (most websites that need tools like this are more than 1 language, or use a CMS for copy/text)

my main problem is that select was choosing options that didn't even have values on them. the copy was completely breaking things because select just looks for words, not full copy. my options reuse words, and now this select function is demanding that i write my copy in a certain way, or my tests break. at the very least it shouldn't return an option that isn't a valid form submission (no value).

if you don't want to change the behaviour, then i think adding clear edge cases to the documentation should be done.

```html
                    <select
                        id="company_class"
                        name="company-class"
                        emit-on-change="company-class:select"
                        required>

                        <option value="" hidden> Select a Company Type </option>

                        <optgroup label="Capital Allocator">
                            <option value="investor.class/individual"> Individual </option>
                            <option value="investor.class/company"> Company </option>
                        </optgroup>

                        <optgroup label="Capital Raiser">
                            <option value="manager.class/investment-sponsor"> Investment Sponsor </option>
                            <option value="manager.class/broker-agent"> Broker or Placement Agent </option>
                            <option value="manager.class/startup"> Startup or SME </option>
                        </optgroup>
                    </select>
```

here is an example where if i do `(select d :company_class "Company")` it returns the placeholder, not the company option `<option value="" hidden> Select a Company Type </option>` it's a nonsense return, no value, hidden (display none), not selectable by the user at all. and i can't get the option that actaully does match the full text of what i'm searching for. selecting by value is the only sensible API, with text, and subtext (current behaviour) being brittle fallbacks.

`(e/click driver [{:tag :select :id :myselect} {:tag :option :value "foo3"}])` looks like the closest thing to what i want to have as an API. makes select look a bit redundant.

**Comment by boxxxie** [comment]
i have updated my custom select function to 
```(defn select-value [driver id value]
  (e/click driver
           [{:id id}
            {:value value}]))
```

**Comment by lread** [comment]
Hey @boxxxie, thanks for taking the time to respond.

> thanks for the reply

Glad you appreciate it, I spent a lot of time on it!

> if select worked the way you describe, i wouldn't have had a bad experience with it, but i still would have preferred value based selection.

I don't understand, was my description wrong?

> the way it currently works, and the way you think it should work, are both buggy.

I'm not sure what you mean by buggy? Do you really mean non-obvious or hard to use?

> being forced to write xpath to use this type of API is too much, i think my example workaround shows that it's very easy to avoid doing something like that

You don't have to write Xpath. You can use the vector syntax as I showed above:

```Clojure
(e/click driver [{:tag :select :id :myselect} {:tag :option :value "foo3"}])
```
Or to match your updated select function more closely:
```Clojure
(e/click driver [{:id :myselect} {:value "foo3"}])
```

**Comment by lread** [comment]
> i have updated my custom select function to
> 
> ```clojure
> (defn select-value [driver id value]
>   (e/click driver
>            [{:id id}
>             {:value value}]))
> ```

Coolio. So all good? I still think an update to the docstring might help avoid confusion.
What do you think?

**Comment by boxxxie** [comment]
explanation of why select is no the same as what you describe
```clojure
(defn select
  "Have `driver` select option with matching `text` for select element found by query `q`.
  The select element is clicked, then the option.

  See [[query]] for details on `q`."
  [driver q text]
  (let [select-el (query driver q)]
    (click-el driver select-el)
    (let [option-el (query driver q {:tag :option :fn/has-text text})]
      (click-el driver option-el))))
```

the behaviour you describe is as if the options for the query in select are `{:tag :option :fn/text text}` but they are in fact `{:tag :option :fn/has-text text}` which is very very different and why i ran into poor behaviour. `has-text` is why `select` was returning non-sense when i tried to use it on my code, "Company" occurs in a few places, and it picked the first place, even though it's not an exact match and an exact match exists.


i think that since you think the behaviour is different from the actual implementation, and my *bug* is related to the same issue, that the docs should be updated, or that the behaviour should change, and probably both should be done.


---
thanks for your help, i was able to make a much better function for my purpose, and after all this i actually feel that `select` is super redundant and probably should be deprecated :) the solution you told me about is so much more powerful and intuitive.

**Comment by lread** [comment]
Ah. Ok. I think I finally understand your issue after all these words we have exchanged here! :slightly_smiling_face: `fn/has-text` vs `fn/text`.

I probably won't change the behaviour because that would be breaking for existing users.
I'll update the docstring.

I'll likely also add a section in the user guide about selecting options, and go over some examples.
