### ISSUE TITLE
e/click doesn't work on Safari 16

### ISSUE THREAD

**Issue by davidyang** [clj-commons/etaoin#557]
**Version**
1.0.40

**Platform**
Operating System: OSX Ventura 13.5, Safari 16

Browser vendor: Safari
Browser version: 16
WebDriver version: % safaridriver --version Included with Safari 16.6 (18615.3.12.11.2)

**Symptom**
e/click doesn't seem to click the button or trigger any onclick events.  This works though:

`  (e/js-execute driver "document.getElementsByTagName('button')[0].click()")`

**Diagnosis**
There's seems to have been an issue with Safari 13 and WebDriver clicks but it looks to have been resolved several years ago.  I can't find any recent issues on SafariDriver that would indicate this would still be a problem.

**Comment by davidyang** [comment]
Apologies, this is a known issue:

https://github.com/clj-commons/etaoin/blob/master/doc/01-user-guide.adoc#clicking-on-a-link-does-not-work-with-safari

**Comment by lread** [comment]
No prob @davidyang, thanks for following up!
