### ISSUE TITLE
Document all :fn/* query pseudo-functions in a definitive list

### ISSUE THREAD

**Issue by dgr** [clj-commons/etaoin#602]
The Selecting Elements section of the User Guide, in the Map Syntax Queries subsection, documents a set of rules for map syntax. The last "rule" is "`:fn/` is a prefix followed by a supported query function." The Selecting Elements section of the guide mentions a number of these `:fn/*` "functions" in various examples, but the guide doesn't provide a definitive list.

The User Guide should contain a definitive list of `:fn/*` functions.

The User Guide mentions:
* `:fn/text`
* `:fn/has-text`
* `:fn/has-class`
* `:fn/has-classes`
* `:fn/link`
* `:fn/enabled`
* `:fn/disabled`

Looking through `impl/xpath.clj`, it appears that `:fn/has-string` is also valid, although that doesn't appear in the User Guide.

**Comment by dgr** [comment]
I should have also added that if that is the list, I can submit a PR with documentation changes to add the list along with concise descriptions of each.

**Comment by lread** [comment]
Great idea @dgr! A PR is most welcome.

**Comment by lread** [comment]
Addressed by #605
