### ISSUE TITLE
Get stricter when unwrapping elements

### ISSUE THREAD

**Issue by lread** [clj-commons/etaoin#620]
## Currently
When Etaoin digs out an element id from a WebDriver response, it does so like this:

`(-> ... second first)`

## But
@dgr recently added an `unwrap-webdriver-object`, which he used when adding shadow dom support.

If it does not get the expected response from the WebDriver it actually throws.

I think this is more user-friendly than the current lax behaviour. 

## So
I think Etaoin should make use of Dave's new internal function when digging out element ids from WebDriver responses.

**Comment by dgr** [comment]
If you want, I'm happy to submit a PR for this.

**Comment by lread** [comment]
Yeah, that would be great, thanks @dgr!
