### ISSUE TITLE
Update `fill-human*` doc strings

### ISSUE THREAD

**Issue by dgr** [clj-commons/etaoin#637]
Today, the `fill-human*` doc strings all give a description of the `opts` parameter that controls the "human-ness" of the input. Rather than repeating this in all of the doc strings, the user should be pointed at the doc string in `fill-human-el` which is the function that actually implements those parameters. This is similar to how the doc strings of numerous API functions refer the user back to `query` for a description of the `q` parameter. I'll submit a PR for this shortly.

**Comment by lread** [comment]
Closed by #641
