### ISSUE TITLE
Deprecate `when-predicate` and `when-not-predicate` macros

### ISSUE THREAD

**Issue by dgr** [clj-commons/etaoin#644]
**Problem/Opportunity**
These macros are currently listed as part of the Etaoin public API, but they are basically just a very thin wrapper around clojure.core's `when` and `when-not`. The value for keeping them as part of the Etaoin API is very low.

**Proposed Solution**
Mark these two macros as deprecated. Remove all usage of these macros from the Etaoin code base itself. Remove these macros from Etaoin during the next major breaking change release.

**Alternative Solutions**
We could leave them in the code base for forward compatibility. Given the low value delivered by these macros, it's best if they are gracefully removed over time.

**Action**
I'll submit a PR that deprecates them, removes them from the API documentation TOC, and updates CHANGELOG with a description of what is being done and what users should do instead.

**Comment by lread** [comment]
Thanks @dgr! And good on you for noticing these little oddities!

You could put the meat of "what users should do instead" in the docstrings and refer to that from the changelog. 

Deprecate them for sure, and declare them candidates for deletion, but we may never delete them. They could be just a couple of weird historical warts.
