### ISSUE TITLE
Fix documentation associated with `query` parameter `q` being a string

### ISSUE THREAD

**Issue by dgr** [clj-commons/etaoin#656]
Today, Etaoin's documentation states that when `query` is given a string for its `q` parameter, the string is interpreted as an XPath query. This is only partially true. In reality, the string is interpreted as either XPath or CSS, depending on the `:locator` associated with the driver. By default, drivers are initialized with `:locator` set to `"xpath"`, but this may be changed using the `use-css` function and the `with-css` macro. In that case, the string is interpreted as a CSS formatted locator.

The documentation (both doc string for `query` as well as User Guide description of `query`'s `q` parameter) should be corrected.

**Comment by lread** [comment]
Ok, PR welcome!
