### ISSUE TITLE
Make `set-<xyz>-timeout` functions more resilient

### ISSUE THREAD

**Issue by dgr** [clj-commons/etaoin#657]
**Version**
1.1.41

**Platform**
All

**Symptom**
Passing a non-integer value (e.g., a rational or double) to the `set-<xyz>-timeout` functions may result in an error.

**Reproduction**
Passing values such as `100/3` (a rational that should result in a timeout of approximately 33 seconds) results in an error. Similarly, passing `1.33333` seconds (a double that should result in a timeout of approximately 1 and 1/3 seconds) results in an error.

**Actual behavior**
The WebDriver returns an error and Etaoin throws an exception.

**Expected behavior**
Etaoin should be doing whatever conversions are necessary and dealing with Clojure's numerics to get the final result to be something that WebDriver will accept (within WebDriver's limits).

**Diagnosis**
The WebDriver Set Timeouts API specifies timeouts in milliseconds. The Etaoin `set-<xyz>-timeout` functions specify the timeout in seconds. Under the hood, Etaoin is converting seconds to milliseconds by multiplying by 1000, but it doesn't coerce the final value to an integer. Instead it passes on the resulting Clojure number, which could be a rational or double, to WebDriver, which then throws an error.

**Action**
I'll submit a PR to make the internal `etaoin.impl.util/sec->ms` routine more robust.

**Comment by lread** [comment]
Dave, I don't really care about this level of detail for Etaoin, but if you want to submit a fix, that's ok with me.  Another option would be to deprecate the `get/set-blah-timeout` in favour of the ones that set and get all values.
