### ISSUE TITLE
Better error handling by replacing `etaoin.impl.util/error` with `throw+`

### ISSUE THREAD

**Issue by dgr** [clj-commons/etaoin#666]
**Problem/Opportunity**
Etaoin has an inconsistent strategy for throwing exceptions. Sometimes, it uses Slingshot with a fairly detailed map, including a `:type` key, a detailed `:message`, and whatever other data might be useful to a human trying to debug a problem. In five instances, however, it calls a small utility function, `etaoin.impl.util/error` which simply throws an extremely generic `java.lang.Exception` with a sometimes cryptic error message. This is a lot less useful than throwing a map with Slingshot.

**Proposed Solution**
Replace calls to `etaoin.impl.util/error` with a call to Slingshot's `throw+` with more detailed information about the error in the thrown map.

**Action**
I'll submit a PR.

**Comment by lread** [comment]
This is unimportant to me and, technical, a very minor breaking change.

How important is this to you and users of Etaoin?
