### ISSUE TITLE
Implement WebDriver New Window function

### ISSUE THREAD

**Issue by dgr** [clj-commons/etaoin#679]
**Problem/Opportunity**
Today, Etaoin has functions to switch among browser windows and close them, but it does not implement the WebDriver New Window function to create them.

**Proposed Solution**
Implement a `new-window` function that is based on the WebDriver New Window endpoint.

**Alternative Solutions**
None. There is no way to create new windows other than the load specific HTML into the browser that opens a link in a new window/frame and to click on that link. In fact, that's what the current Etaoin test suite does to create a new window so that it can validate that it can switch between windows correctly.

**Additional context**
None.

**Action**
I can submit a PR.

**Comment by lread** [comment]
Seems like there is decent support for it: https://wpt.fyi/results/webdriver/tests/classic/new_window/new_window.py?label=master&label=experimental&aligned

PR is welcome.
