### ISSUE TITLE
Issues with switch-frame and scroll-query

### ISSUE THREAD

**Issue by sofiiahitlan** [clj-commons/etaoin#686]
**Version**
1.0.40

**Platform**
Operating System: Windows 10, 64 bit
Clojure version: 1.11.0
Babashka version: 0.5.22
JDK vendor and version: OpenJDK 64-Bit Server VM 16.0.2+7

Browser vendor: chrome
Browser version: 131.0.6778.109
WebDriver version: 131.0.6778.87

**Symptom**
Around 11/22/2024 two of the Etaoin's functions stopped working for us - `switch-frame` and `scroll-query` (other functions are fine).  They seem to be working when I upgrade to v. 1.1.42 but we can't switch to it just yet so hoping to get some ideas on what could be wrong.
Scrolling works when I use `js-execute` functionality instead. Unfortunately, I couldn't figure our how to replace `switch-frame` with `js-execute`. We haven't released any code or switched versions on that day so I'm unsure what might have happened.

Stack trace for `switch-frame` even though I confirmed with `visible?` that frame in fact exists:
`throw+: {:response {:sessionId "7a730464ed7f99a4f8672e60303b8f85", :status 8, :value {:message "no such frame\n  (Session info: chrome=131.0.6778.109)\n  (Driver info: chromedriver=131.0.6778.87 (ce31cae9487357cfd3bd62984ed5250121a71a23-refs/branch-heads/6778@{#2287}),platform=Windows NT 10.0.17763 x86_64)"}}, :path "session/7a730464ed7f99a4f8672e60303b8f85/frame", :payload {:id {:ELEMENT "f.4D97810BBE8057539696C861A0D78B00.d.67BD230811358DEB0C3EE3367EEDD6D3.e.205", :element-6066-11e4-a52e-4f735466cecf "f.4D97810BBE8057539696C861A0D78B00.d.67BD230811358DEB0C3EE3367EEDD6D3.e.205"}}, :method :post, :type :etaoin/http-error, :port 52054, :host "127.0.0.1", :status 200, :webdriver-url nil, :driver {:args ("chromedriver" "--port=52054"), :capabilities {:loggingPrefs {:browser "ALL"}, :chromeOptions {:args ("--window-size=1400,850"), :prefs {:download.default_directory "C:\\Users\\popautodev\\Downloads\\", :download.prompt_for_download false, :download.directory_upgrade true, :plugins.always_open_pdf_externally true}}, :pageLoadStrategy :none}, :process {:proc #object[java.lang.ProcessImpl 0x528e25b1 "Process[pid=2852, exitValue=\"not exited\"]"], :exit nil, :in #object[java.io.BufferedOutputStream 0x40977b57 "java.io.BufferedOutputStream@40977b57"], :out #object[java.lang.ProcessBuilder$NullInputStream 0x27f845d9 "java.lang.ProcessBuilder$NullInputStream@27f845d9"], :err #object[java.lang.ProcessBuilder$NullInputStream 0x27f845d9 "java.lang.ProcessBuilder$NullInputStream@27f845d9"], :prev nil, :cmd ["chromedriver" "--port=52054"]}, :locator "xpath", :type :chrome, :port 52054, :host "127.0.0.1", :url "http://127.0.0.1:52054", :session "7a730464ed7f99a4f8672e60303b8f85"}}`

Stack trace for `scroll-query` (element isn't in fact undefined; `visible?` returns true):
`raw error clojure.lang.ExceptionInfo: throw+: {:response {:sessionId "bdbaf6e99b6ba82eda75c6435cb5e38a", :status 17, :value {:message "javascript error: Cannot read properties of undefined (reading 'scrollIntoView')\n  (Session info: chrome=131.0.6778.86)\n  (Driver info: chromedriver=131.0.6778.85 (3d81e41b6f3ac8bcae63b32e8145c9eb0cd60a2d-refs/branch-heads/6778@{#2285}),platform=Windows NT 10.0.17763 x86_64)"}}, :path "session/bdbaf6e99b6ba82eda75c6435cb5e38a/execute", :payload {:script "arguments[0].scrollIntoView();", :args [{:ELEMENT "f.932D072749978457BB66B88CB92E87F7.d.F4D5810368CE9DF7FC49001D8AAFDC73.e.308", :element-6066-11e4-a52e-4f735466cecf "f.932D072749978457BB66B88CB92E87F7.d.F4D5810368CE9DF7FC49001D8AAFDC73.e.308"}]}, :method :post, :type :etaoin/http-error, :port 28443, :host "127.0.0.1", :status 200, :webdriver-url nil, :driver {:args ("chromedriver" "--port=28443"), :capabilities {:loggingPrefs {:browser "ALL"}, :chromeOptions {:prefs {:download.default_directory "C:\\Users\\popautodev\\Desktop\\skyscraper\\61981\\", :download.prompt_for_download false, :download.directory_upgrade true, :plugins.always_open_pdf_externally true}, :args ("--window-size=1400,850" "--load-extension=C:\\Users\\popautodev\\Desktop\\skyscraper\\proxy-defs\\smartproxy" "--disable-gpu")}, :pageLoadStrategy :none}, :process {:proc #object[java.lang.ProcessImpl 0x7cfdaf88 "java.lang.ProcessImpl@7cfdaf88"], :exit nil, :in #object[java.io.BufferedOutputStream 0x36f269b9 "java.io.BufferedOutputStream@36f269b9"], :out #object[java.lang.ProcessBuilder$NullInputStream 0x77bab1c9 "java.lang.ProcessBuilder$NullInputStream@77bab1c9"], :err #object[java.lang.ProcessBuilder$NullInputStream 0x77bab1c9 "java.lang.ProcessBuilder$NullInputStream@77bab1c9"], :prev nil, :cmd ["chromedriver" "--port=28443"]}, :locator "xpath", :type :chrome, :port 28443, :host "127.0.0.1", :url "http://127.0.0.1:28443", :session "bdbaf6e99b6ba82eda75c6435cb5e38a"}}`

**Reproduction**
Call `switch-frame` or `with-frame` functions on visible/existent frames. Use `scroll-query` to scroll to visible element

**Actual behavior**
Can't switch to frame even though it's visible, can't scroll to visible element

**Expected behavior**
Can successfully switch to frame, can scroll

**Diagnosis**
Not yet

**Action**
TBD

Thank you!!!

**Comment by lread** [comment]
Hi @sofiiahitlan, thanks for reaching out!

Sorry, as a volunteer maintainer of Etaoin, I can only (barely!) support the current release.

I'm curious: what is preventing you from upgrading?

**Comment by sofiiahitlan** [comment]
@lread Thank you for your time. Your work is greatly appreciated. We decided to go ahead and upgrade the version as it was the only option we had.

**Comment by lread** [comment]
Thanks for following up, @sofiiahitlan! Glad you are sorted out.
